### PR TITLE
Rename getParamKeys to getParams

### LINKED ISSUE #71: getParamKeys is confusing / not named properly
The "getParamKeys" method is really implemented to return the param values (not keys) at the moment.

```
/**
* Get all parameter keys.
*
* @return {string[]} this parameter key array
*/
PubfoodObject.prototype.getParamKeys = function() {
  var ret = [];
  for (var i in this.params_) {
    ret.push(this.params_[i]);
  }
  return ret;
};
```

Maybe rename getParamKeys to getParams and setup a new method that really returns the keys?

### PR DESCRIPTION
**Pull request by mangalambigai**
Add new getParamKeys function to return keys. Fixes #71

### CODE REVIEW

**Comment by elljoh** [comment]
Looking good. As additional coverage, could you add a test that verifies multiple key values in addition to the key count?

Thanks for adding tests for the single key value.

There was a gap previously in tests to confirm that key values matched what was provided, so will be good generally to cover this.

A case in point is the existing test here:
 - https://github.com/pubfood/pubfood/blob/master/test/pubfoodobject.js#L84

It would be prudent to have confirmation that while there are five keys, should be the correct five keys. This has been the missing type of test I am thinking of.

**Comment by mangalambigai** [comment]
You are correct. Just added the tests. 
Please review and let me know if anything else needs change.

**Comment by elljoh** [comment]
Apologies on the merge delay of this.

I have been thinking about the utility value of the functions to get/set parameters. For example, if we look at this Pulsepoint example, [pulsepoint.html#L242-L246](https://github.com/pubfood/pubfood/blob/master/examples/provider/bid/pulsepoint/pulsepoint.html#L242-L246), the intent is to be able to set parameters with a namespace so that we can identify parameter values as pertaining to a specific contextual namespace; in this use case a BidProvider specific and/or publisher specific parameters.

e.g. 
```
var slot = pf.getSlot("/1066621/ExchangeTech-PrebidTest")

slot.setParam('openx', {foo: 'bar'})

slot.getParamKeys()
["pulsepoint", "openx"]

slot.getParams()
// pretty out for illustration
[
  {
    "cp": 521732,
    "ct": 147007,
    "cf": "728X90",
    "placementCode": "/1066621/ExchangeTech-PrebidTest",
    "elementId": "div-leaderboard"
  },
  {
    "foo": "bar"
  }
]
```

We can still getParam by known namespace i.e.
```
slot.getParam('openx')
Object {foo: "bar"}
slot.getParam('pulsepoint')
Object {cp: 521732, ct: 147007, cf: "728X90", placementCode: "/1066621/ExchangeTech-PrebidTest", elementId: "div-leaderboard"}
```

**Comment by mangalambigai** [comment]
Just thinking out loud here, would it be more useful for getParams to return the keys as well as values? 
```sh
[
  { 
   key: "pulsepoint",
   value: 
   { 
    "cp": 521732,
    "ct": 147007,
    "cf": "728X90",
    "placementCode": "/1066621/ExchangeTech-PrebidTest",
    "elementId": "div-leaderboard"
   }
  },
  {
    key: "openx",
    value: 
    {
    "foo": "bar"
    }
  }
]
```

**Comment by elljoh** [comment]
@mangalambigai made a change to have `pubfoodobject.getParams()` to simply return the params object. Decided not to clone the object, but we can do this.

Lmk what you think.

**Pull request merged**
