### PR TITLE
Improve description and add a header bidding diagram

### PR DESCRIPTION
**Pull request by fatihcode**

### CODE REVIEW

**Comment by elljoh** [comment]
Could I ask you to add a relative hyperlink to [LICENSE.txt](https://github.com/pubfood/pubfood/blob/master/LICENSE.txt)?

Since we have the hood up on the README. Thanks!

**Comment by fatihcode** [comment]
Do you mean replacing the URL at https://github.com/pubfood/pubfood/blob/master/LICENSE.txt#L3 with Github URL? Or adding both?

**Comment by elljoh** [comment]
I mean the filename `LICENSE.txt` below should be linked to the actual [LICENSE.txt](https://github.com/pubfood/pubfood/blob/master/LICENSE.txt) file.

https://github.com/pubfood/pubfood/blame/master/README.md#L56

> For the full copyright and license information, please view the **_LICENSE.txt_** file.

**Comment by fatihcode** [comment]
done

**Pull request merged**
